const RESOURCES = [
  {
    id: 1,
    cat: 'crisis',
    type: 'hotline',
    name: 'Veterans Crisis Line',
    desc: 'Free confidential support 24/7. Call 988 press 1, text 838255, or chat online.',
    phone: '988, Press 1',
    url: 'https://veteranscrisisline.net',
    label: 'Visit Website',
  },
  {
    id: 2,
    cat: 'crisis',
    type: 'state',
    name: 'Alabama Dept. of Mental Health — Veteran Services',
    desc: 'State-funded mental health services including outpatient counseling, substance abuse treatment, and crisis stabilization.',
    phone: '(800) 367-0955',
    url: 'https://mh.alabama.gov',
    label: 'Learn More',
  },
  {
    id: 3,
    cat: 'crisis',
    type: 'federal',
    name: 'VA Caregiver Support Line',
    desc: 'Support for those caring for veterans with mental health challenges, TBI, or serious conditions.',
    phone: '(855) 260-3274',
    url: 'https://www.caregiver.va.gov',
    label: 'Learn More',
  },
  {
    id: 4,
    cat: 'crisis',
    type: 'nonprofit',
    name: 'Give an Hour',
    desc: 'Free mental health care for post-9/11 military and families. Connects veterans with licensed mental health professionals.',
    phone: '',
    url: 'https://giveanhour.org',
    label: 'Find a Provider',
  },
  {
    id: 5,
    cat: 'crisis',
    type: 'federal',
    name: 'VA Mental Health Services',
    desc: 'Comprehensive mental health services through VA Alabama — PTSD, MST, depression, and substance use treatment.',
    phone: '(800) 827-1000',
    url: 'https://www.va.gov/health-care/health-needs-conditions/mental-health',
    label: 'Learn More',
  },
  {
    id: 6,
    cat: 'crisis',
    type: 'nonprofit',
    name: 'Centerstone Military Services',
    desc: 'Confidential mental health and substance use services for military members, veterans, and families.',
    phone: '(877) 974-7468',
    url: 'https://centerstone.org/our-services/military-services',
    label: 'Get Help',
  },
  {
    id: 7,
    cat: 'crisis',
    type: 'nonprofit',
    name: 'Warrior PATHH — Boulder Crest',
    desc: 'Free Post-Traumatic Growth retreats for combat veterans and first responders. Travel and lodging included.',
    phone: '(540) 554-7442',
    url: 'https://bouldercrest.org/programs',
    label: 'Apply Now',
  },
  {
    id: 8,
    cat: 'crisis',
    type: 'nonprofit',
    name: 'SAFER Together',
    desc: 'Suicide prevention program connecting veterans with peer support specialists and mental health resources.',
    phone: '',
    url: 'https://www.safertogetheral.org',
    label: 'Learn More',
  },
  {
    id: 75,
    cat: 'crisis',
    type: 'nonprofit',
    name: 'Uwill — Free Teletherapy',
    desc: 'Free teletherapy and wellness sessions for Alabama veterans ages 18&ndash;34, in partnership with the Alabama Dept. of Mental Health.',
    phone: '',
    url: 'https://uwill.com/alabama-veterans-mental-health/',
    label: 'Get Started',
  },
  {
    id: 76,
    cat: 'recovery',
    type: 'local',
    name: 'Vets Recover — Mobile, AL',
    desc: 'Peer support and recovery resources for veterans in the Mobile area. 24/7 line.',
    phone: '(251) 405-3677',
    url: 'https://www.vetsrecover.org',
    label: 'Learn More',
  },
  {
    id: 77,
    cat: 'recovery',
    type: 'local',
    name: 'Turning Point Foundation — Thorsby, AL',
    desc: 'Faith-based recovery and mental health support serving veterans in central Alabama.',
    phone: '(205) 955-2890',
    url: 'https://www.turningpointal.org',
    label: 'Learn More',
  },
  {
    id: 9,
    cat: 'vetcenters',
    type: 'federal',
    name: 'Birmingham VA Medical Center',
    desc: 'Full-service VA center with mental health, primary care, surgery, and specialty services.',
    phone: '(205) 933-8101',
    url: 'https://www.va.gov/birmingham-health-care',
    label: 'Visit Website',
  },
  {
    id: 10,
    cat: 'vetcenters',
    type: 'federal',
    name: 'Tuscaloosa VA Medical Center',
    desc: 'VA medical center providing mental health, primary care, and long-term care services.',
    phone: '(205) 554-2000',
    url: 'https://www.va.gov/central-alabama-health-care',
    label: 'Visit Website',
  },
  {
    id: 11,
    cat: 'vetcenters',
    type: 'federal',
    name: 'Central Alabama VAHCS — Montgomery',
    desc: 'VA health care system with outpatient care, mental health, and specialty services.',
    phone: '(334) 272-4670',
    url: 'https://www.va.gov/central-alabama-health-care',
    label: 'Visit Website',
  },
  {
    id: 12,
    cat: 'vetcenters',
    type: 'federal',
    name: 'Central Alabama VAHCS — Tuskegee',
    desc: 'Historic VA campus offering full inpatient and outpatient services.',
    phone: '(334) 727-0550',
    url: 'https://www.va.gov/central-alabama-health-care',
    label: 'Visit Website',
  },
  {
    id: 13,
    cat: 'vetcenters',
    type: 'federal',
    name: 'Gulf Coast VA — Mobile',
    desc: 'VA health care serving southwest Alabama and the Gulf Coast region.',
    phone: '(251) 219-3900',
    url: 'https://www.va.gov/gulf-coast-health-care',
    label: 'Visit Website',
  },
  {
    id: 14,
    cat: 'vetcenters',
    type: 'federal',
    name: 'VA Mission Act — Community Care',
    desc: 'Receive care from community providers when VA cannot provide timely access.',
    phone: '(866) 606-8198',
    url: 'https://www.va.gov/communitycare',
    label: 'Learn More',
  },
  {
    id: 15,
    cat: 'vetcenters',
    type: 'federal',
    name: 'VA Telehealth Services',
    desc: 'VA video and phone health appointments statewide — no travel required.',
    phone: '(866) 606-8198',
    url: 'https://telehealth.va.gov',
    label: 'Learn More',
  },
  {
    id: 16,
    cat: 'vetcenters',
    type: 'federal',
    name: 'VA Women Veterans Health Care',
    desc: 'Primary care, mental health, reproductive health, and MST care for women veterans.',
    phone: '(855) 829-6636',
    url: 'https://www.va.gov/health-care/health-needs-conditions/womens-health-needs',
    label: 'Learn More',
  },
  {
    id: 17,
    cat: 'vetcenters',
    type: 'state',
    name: 'Alabama ADVA — 62 County Offices',
    desc: 'Every Alabama county has a Veterans Service Officer who can help with benefits, claims, and referrals — at no cost.',
    phone: '(334) 242-5077',
    url: 'https://va.alabama.gov',
    label: 'Find Your County',
  },
  {
    id: 18,
    cat: 'housing',
    type: 'federal',
    name: 'HUD-VASH Program',
    desc: 'Housing vouchers combined with VA supportive services for homeless veterans.',
    phone: '(800) 827-1000',
    url: 'https://www.va.gov/homeless/hud-vash.asp',
    label: 'Learn More',
  },
  {
    id: 19,
    cat: 'housing',
    type: 'federal',
    name: 'VA Supportive Services (SSVF)',
    desc: 'Rapid rehousing and prevention assistance for very low-income veteran families.',
    phone: '(877) 737-0111',
    url: 'https://www.va.gov/homeless/ssvf',
    label: 'Learn More',
  },
  {
    id: 20,
    cat: 'housing',
    type: 'state',
    name: 'Alabama Housing Finance Authority',
    desc: 'Down payment assistance, low-interest mortgages, and veteran-specific housing options.',
    phone: '(334) 244-9200',
    url: 'https://ahfa.com',
    label: 'Visit Website',
  },
  {
    id: 21,
    cat: 'housing',
    type: 'federal',
    name: 'VA Home Loan Guarantee',
    desc: 'No down payment home loans for eligible veterans, service members, and surviving spouses.',
    phone: '(877) 827-3702',
    url: 'https://www.va.gov/housing-assistance/home-loans',
    label: 'Learn More',
  },
  {
    id: 22,
    cat: 'housing',
    type: 'nonprofit',
    name: 'Volunteers of America — Alabama',
    desc: 'Transitional housing and supportive services for homeless veterans across Alabama.',
    phone: '(205) 323-4462',
    url: 'https://voase.org',
    label: 'Learn More',
  },
  {
    id: 23,
    cat: 'housing',
    type: 'nonprofit',
    name: 'Habitat for Humanity Veterans Build',
    desc: 'Affordable homeownership for veterans. Local Alabama Habitat affiliates participate.',
    phone: '(229) 924-6935',
    url: 'https://www.habitat.org/our-work/veteran-homeownership',
    label: 'Learn More',
  },
  {
    id: 24,
    cat: 'housing',
    type: 'state',
    name: 'Alabama Emergency Homeowner Assistance',
    desc: 'Emergency mortgage assistance for Alabama veterans facing foreclosure or housing instability.',
    phone: '(800) 325-4606',
    url: 'https://ahfa.com/homebuyers/homeowners-assistance-program',
    label: 'Learn More',
  },
  {
    id: 25,
    cat: 'housing',
    type: 'nonprofit',
    name: 'National Coalition for Homeless Veterans',
    desc: 'National advocacy and resource network including local Alabama service providers.',
    phone: '(800) 838-4357',
    url: 'https://nchv.org',
    label: 'Find Resources',
  },
  {
    id: 87,
    cat: 'housing',
    type: 'nonprofit',
    name: 'Priority Veteran — United Way',
    desc: 'Connects homeless veterans to medical care, mental health services, benefits, and employment.',
    phone: '(866) 460-3827',
    url: 'https://www.priorityveteran.org',
    label: 'Get Help',
  },
  {
    id: 88,
    cat: 'housing',
    type: 'nonprofit',
    name: 'VOA Southeast',
    desc: 'Transitional housing, health care, financial planning, child care, legal assistance, and transportation for veteran families.',
    phone: '(251) 415-6645',
    url: 'https://voase.org',
    label: 'Learn More',
  },
  {
    id: 89,
    cat: 'housing',
    type: 'nonprofit',
    name: 'Hope for All Gulf Coast',
    desc: 'Housing assistance, financial planning, and transportation to veterans in South Alabama (Mobile and Baldwin counties).',
    phone: '(251) 450-3345',
    url: 'https://hfal.org',
    label: 'Learn More',
  },
  {
    id: 26,
    cat: 'benefits',
    type: 'state',
    name: 'Alabama Dept. of Veterans Affairs',
    desc: 'Primary state agency for veteran benefits. Free claims assistance at every Alabama county courthouse.',
    phone: '(334) 242-5077',
    url: 'https://va.alabama.gov',
    label: 'Visit Website',
  },
  {
    id: 27,
    cat: 'benefits',
    type: 'federal',
    name: 'VA Benefits Administration',
    desc: 'Federal VA benefits: disability, pension, education, home loans, insurance, and burial.',
    phone: '(800) 827-1000',
    url: 'https://www.va.gov/decide-benefit',
    label: 'Apply Now',
  },
  {
    id: 28,
    cat: 'benefits',
    type: 'nonprofit',
    name: 'Disabled American Veterans (DAV)',
    desc: 'Free claims assistance and VA benefits advocacy. Alabama DAV chapters statewide.',
    phone: '(877) 426-2838',
    url: 'https://www.dav.org',
    label: 'Get Help',
  },
  {
    id: 29,
    cat: 'benefits',
    type: 'nonprofit',
    name: 'American Legion — Alabama',
    desc: 'Accredited VSOs to help with claims, appeals, and advocacy.',
    phone: '(334) 262-6638',
    url: 'https://www.alabamalegion.org',
    label: 'Find a Post',
  },
  {
    id: 30,
    cat: 'benefits',
    type: 'nonprofit',
    name: 'VFW — Alabama',
    desc: 'Service officers provide free VA claims and benefits assistance across Alabama.',
    phone: '(334) 261-1083',
    url: 'https://vfw.org',
    label: 'Find a Post',
  },
  {
    id: 31,
    cat: 'benefits',
    type: 'federal',
    name: 'PACT Act — Toxic Exposure',
    desc: 'Expanded VA benefits for veterans exposed to burn pits, Agent Orange, and other toxins.',
    phone: '(800) 827-1000',
    url: 'https://www.va.gov/resources/the-pact-act-and-your-va-benefits',
    label: 'Learn More',
  },
  {
    id: 32,
    cat: 'benefits',
    type: 'nonprofit',
    name: 'AMVETS — Alabama',
    desc: 'Free VSO assistance with VA claims and benefits.',
    phone: '',
    url: 'https://alamvets.org',
    label: 'Learn More',
  },
  {
    id: 33,
    cat: 'education',
    type: 'federal',
    name: 'Post-9/11 GI Bill (Chapter 33)',
    desc: 'Covers tuition, fees, housing, and books for veterans with 90+ days post-9/11 service.',
    phone: '(888) 442-4551',
    url: 'https://www.va.gov/education/about-gi-bill-benefits/post-9-11',
    label: 'Apply Now',
  },
  {
    id: 34,
    cat: 'education',
    type: 'federal',
    name: 'VA Vocational Rehabilitation',
    desc: 'Education and employment for veterans with service-connected disabilities. Covers tuition, books, and living expenses.',
    phone: '(800) 827-1000',
    url: 'https://www.va.gov/careers-employment/vocational-rehabilitation',
    label: 'Learn More',
  },
  {
    id: 35,
    cat: 'education',
    type: 'state',
    name: 'Alabama G.I. Dependents Scholarship',
    desc: 'Up to 5 years of tuition at any Alabama state college for dependents of qualifying veterans.',
    phone: '(334) 242-5077',
    url: 'https://va.alabama.gov/education-benefits',
    label: 'Apply Now',
  },
  {
    id: 36,
    cat: 'education',
    type: 'state',
    name: 'Alabama National Guard Education Assistance',
    desc: 'Financial assistance for Alabama National Guard members enrolled in degree programs.',
    phone: '(334) 271-7474',
    url: 'https://al.ng.mil',
    label: 'Learn More',
  },
  {
    id: 37,
    cat: 'education',
    type: 'nonprofit',
    name: 'Folds of Honor Foundation',
    desc: 'Scholarships for spouses and children of fallen or disabled servicemembers.',
    phone: '(918) 274-4700',
    url: 'https://foldsofhonor.org',
    label: 'Apply Now',
  },
  {
    id: 38,
    cat: 'education',
    type: 'federal',
    name: 'Survivors & Dependents (Chapter 35)',
    desc: 'Education benefits for spouses and children of veterans who died in service or have total permanent disability.',
    phone: '(888) 442-4551',
    url: 'https://www.va.gov/education/survivor-dependent-education-assistance',
    label: 'Learn More',
  },
  {
    id: 39,
    cat: 'education',
    type: 'nonprofit',
    name: 'Student Veterans of America',
    desc: 'National network of campus student veteran organizations providing peer support and advocacy.',
    phone: '',
    url: 'https://studentveterans.org',
    label: 'Find a Chapter',
  },
  {
    id: 90,
    cat: 'education',
    type: 'state',
    name: 'University of Alabama — Veterans Affairs',
    desc: 'Yellow Ribbon (uncapped), Alabama GI Dependent Scholarship, and military scholarships. Tuscaloosa.',
    phone: '(205) 348-5959',
    url: 'https://vets.sl.ua.edu',
    label: 'Visit Website',
  },
  {
    id: 91,
    cat: 'education',
    type: 'state',
    name: 'UAB — Veterans Services',
    desc: 'Yellow Ribbon (uncapped) for undergrad and grad. Dedicated Veterans Services office in Birmingham.',
    phone: '(205) 934-8804',
    url: 'https://www.uab.edu/students/veterans',
    label: 'Visit Website',
  },
  {
    id: 92,
    cat: 'education',
    type: 'state',
    name: 'Auburn University — Veterans Resource Center',
    desc: 'VA certifications, Yellow Ribbon (75 undergrads/year), and peer support. Auburn, AL.',
    phone: '(334) 844-1974',
    url: 'https://bulletin.auburn.edu/VeteransResourceCenter',
    label: 'Visit Website',
  },
  {
    id: 93,
    cat: 'education',
    type: 'state',
    name: 'Troy University — Military & Veterans Services',
    desc: 'Yellow Ribbon (unlimited), Military Science programs, campuses near Ft. Novosel.',
    phone: '(334) 670-3100',
    url: 'https://troy.edu/admissions/financial-aid/military-benefits.html',
    label: 'Visit Website',
  },
  {
    id: 94,
    cat: 'education',
    type: 'state',
    name: 'UAH — Military & Veterans Services',
    desc: 'Yellow Ribbon (uncapped), near Redstone Arsenal. Strong STEM for transitioning military. Huntsville.',
    phone: '(256) 824-6681',
    url: 'https://www.uah.edu/financial-aid/military',
    label: 'Visit Website',
  },
  {
    id: 95,
    cat: 'education',
    type: 'state',
    name: 'Jacksonville State University — Veterans',
    desc: 'VA certifications, military tuition rates, near Ft. McClellan. Yellow Ribbon participant.',
    phone: '(256) 782-5006',
    url: 'https://www.jsu.edu/financialaid/veterans.html',
    label: 'Visit Website',
  },
  {
    id: 96,
    cat: 'education',
    type: 'state',
    name: 'Alabama State University — Veterans',
    desc: 'VA certifications, disability support, and educational transition resources. Montgomery.',
    phone: '(334) 229-4418',
    url: 'https://www.alasu.edu/accessibility-veteran-affairs',
    label: 'Visit Website',
  },
  {
    id: 97,
    cat: 'education',
    type: 'state',
    name: 'Alabama Community College System',
    desc: 'All 24 Alabama community colleges accept GI Bill and state scholarship programs.',
    phone: '(334) 293-4500',
    url: 'https://www.accs.edu/veterans',
    label: 'Find Your Campus',
  },
  {
    id: 98,
    cat: 'education',
    type: 'state',
    name: 'ADVA — Qualifying State Schools',
    desc: 'Full list of Alabama colleges where the GI Dependents Scholarship can be used.',
    phone: '(334) 242-5077',
    url: 'https://va.alabama.gov/qualifying-state-supported-schools',
    label: 'View Full List',
  },
  {
    id: 40,
    cat: 'employment',
    type: 'state',
    name: 'Alabama Dept. of Labor — Veterans Services',
    desc: 'Priority employment services, job placement, resume help, and training at Alabama Career Centers statewide.',
    phone: '(334) 956-7310',
    url: 'https://labor.alabama.gov/veterans',
    label: 'Visit Website',
  },
  {
    id: 41,
    cat: 'employment',
    type: 'state',
    name: 'Alabama Veterans Resource Center (AVRC)',
    desc: 'Career counseling, job placement, education, and training courses for veterans. Montgomery. Now operating as Mission Forward AL.',
    phone: '(334) 386-5600',
    url: 'https://missionforwardal.org',
    label: 'Visit Website',
  },
  {
    id: 42,
    cat: 'employment',
    type: 'nonprofit',
    name: 'Hire Heroes USA',
    desc: 'Free job placement, resume writing, and career coaching for transitioning military and veterans.',
    phone: '(877) 663-4872',
    url: 'https://www.hireheroesusa.org',
    label: 'Get Help',
  },
  {
    id: 43,
    cat: 'employment',
    type: 'federal',
    name: 'VA Vocational Rehabilitation Employment',
    desc: 'Vocational counseling, training, and job placement for veterans with service-connected disabilities.',
    phone: '(800) 827-1000',
    url: 'https://www.va.gov/careers-employment/vocational-rehabilitation',
    label: 'Learn More',
  },
  {
    id: 44,
    cat: 'employment',
    type: 'nonprofit',
    name: 'RecruitMilitary',
    desc: 'Job fairs and career resources connecting veterans with employers across Alabama and nationwide.',
    phone: '(513) 683-5020',
    url: 'https://recruitmilitary.com',
    label: 'Find Jobs',
  },
  {
    id: 45,
    cat: 'employment',
    type: 'nonprofit',
    name: 'Entrepreneurship Bootcamp for Veterans',
    desc: 'Free business training for post-9/11 veterans at top U.S. universities.',
    phone: '',
    url: 'https://ebv.vets.syr.edu',
    label: 'Apply Now',
  },
  {
    id: 46,
    cat: 'employment',
    type: 'state',
    name: 'Alabama SBDC — Alabama VetStart',
    desc: 'Small business development resources, counseling, and training for veteran entrepreneurs through the Alabama VetStart program.',
    phone: '(205) 934-7260',
    url: 'https://www.asbdc.org/programs/alabama-vetstart/',
    label: 'Learn More',
  },
  {
    id: 47,
    cat: 'employment',
    type: 'federal',
    name: 'USERRA — Employment Rights',
    desc: 'Federal law protecting jobs and benefits of servicemembers when they leave for military duty and return.',
    phone: '(866) 487-2365',
    url: 'https://www.dol.gov/agencies/vets/programs/userra',
    label: 'Learn More',
  },
  {
    id: 48,
    cat: 'financial',
    type: 'state',
    name: 'Alabama Property Tax Exemption',
    desc: 'Veterans rated 100% P&T are exempt from Alabama property taxes. Surviving spouses may also qualify.',
    phone: '(334) 242-1525',
    url: 'https://www.revenue.alabama.gov/property-tax/exemptions-2',
    label: 'Learn More',
  },
  {
    id: 49,
    cat: 'financial',
    type: 'federal',
    name: 'VA Pension Program',
    desc: 'Tax-free pension for wartime veterans with limited income who are 65+ or permanently disabled.',
    phone: '(800) 827-1000',
    url: 'https://www.va.gov/pension',
    label: 'Apply Now',
  },
  {
    id: 50,
    cat: 'financial',
    type: 'nonprofit',
    name: 'Operation Homefront',
    desc: 'Financial assistance grants for active duty and veteran families facing temporary financial hardship.',
    phone: '(210) 659-7756',
    url: 'https://operationhomefront.org',
    label: 'Apply Now',
  },
  {
    id: 51,
    cat: 'financial',
    type: 'nonprofit',
    name: 'DAV Emergency Financial Assistance',
    desc: 'Emergency financial grants for veterans and their families through Alabama DAV chapters.',
    phone: '(877) 426-2838',
    url: 'https://www.dav.org/veterans/emergency-financial-assistance',
    label: 'Get Help',
  },
  {
    id: 52,
    cat: 'financial',
    type: 'nonprofit',
    name: 'American Legion Emergency Fund',
    desc: 'Emergency financial assistance for Legion members, their spouses, and dependent children.',
    phone: '(317) 630-1203',
    url: 'https://www.legion.org/emergency-fund',
    label: 'Learn More',
  },
  {
    id: 53,
    cat: 'financial',
    type: 'nonprofit',
    name: 'VFW Unmet Needs Program',
    desc: 'Grants up to $1,500 for post-9/11 veteran families facing short-term financial hardship.',
    phone: '(816) 756-3390',
    url: 'https://www.vfw.org/assistance/financial-grants',
    label: 'Apply Now',
  },
  {
    id: 54,
    cat: 'financial',
    type: 'state',
    name: 'Alabama Military Family Assistance Fund',
    desc: 'Emergency financial assistance for Alabama National Guard members, Reservists, and their families.',
    phone: '(334) 213-2585',
    url: 'https://dmva.alabama.gov/family-assistance',
    label: 'Learn More',
  },
  {
    id: 55,
    cat: 'legal',
    type: 'nonprofit',
    name: 'Legal Services Alabama',
    desc: 'Free civil legal help for low-income veterans including housing, benefits, family law, and consumer issues.',
    phone: '(866) 456-4995',
    url: 'https://legalservicesalabama.org',
    label: 'Get Help',
  },
  {
    id: 56,
    cat: 'legal',
    type: 'nonprofit',
    name: 'Alabama Law Foundation — Pro Bono',
    desc: 'Coordinates volunteer attorney services for veterans across Alabama.',
    phone: '(334) 269-1515',
    url: 'https://alabamalawfoundation.org',
    label: 'Learn More',
  },
  {
    id: 57,
    cat: 'legal',
    type: 'federal',
    name: 'VA Accredited Attorneys',
    desc: 'Search for VA-accredited claims agents and attorneys who can legally represent you.',
    phone: '',
    url: 'https://www.va.gov/ogc/apps/accreditation/index.asp',
    label: 'Find an Attorney',
  },
  {
    id: 58,
    cat: 'legal',
    type: 'federal',
    name: 'Military OneSource — Legal Consults',
    desc: 'Free legal consultations for active duty members and veterans on a wide range of civil legal issues.',
    phone: '(800) 342-9647',
    url: 'https://www.militaryonesource.mil/legal',
    label: 'Learn More',
  },
  {
    id: 59,
    cat: 'legal',
    type: 'nonprofit',
    name: 'Discharge Upgrade — NVLSP',
    desc: 'Help upgrading a less-than-honorable discharge to access VA benefits and other veteran services.',
    phone: '(202) 265-8305',
    url: 'https://www.nvlsp.org',
    label: 'Learn More',
  },
  {
    id: 60,
    cat: 'legal',
    type: 'nonprofit',
    name: 'UA & Samford Law School Clinics',
    desc: 'Supervised legal help for veterans from University of Alabama and Samford law school clinics.',
    phone: '(205) 348-4960',
    url: 'https://law.ua.edu/clinics',
    label: 'Learn More',
  },
  {
    id: 61,
    cat: 'family',
    type: 'federal',
    name: 'Military OneSource',
    desc: 'Free 24/7 information covering financial counseling, legal help, parenting, deployment support, and more.',
    phone: '(800) 342-9647',
    url: 'https://www.militaryonesource.mil',
    label: 'Learn More',
  },
  {
    id: 62,
    cat: 'family',
    type: 'federal',
    name: 'Dependency and Indemnity Compensation',
    desc: 'Tax-free monthly benefit for surviving spouses, children, and parents of veterans who died in service.',
    phone: '(800) 827-1000',
    url: 'https://www.va.gov/disability/dependency-indemnity-compensation',
    label: 'Apply Now',
  },
  {
    id: 63,
    cat: 'family',
    type: 'nonprofit',
    name: 'TAPS — Tragedy Assistance Program',
    desc: '24/7 support for those who have lost a loved one in military service. Peer support, grief camps, and mentoring.',
    phone: '(800) 959-8277',
    url: 'https://www.taps.org',
    label: 'Get Support',
  },
  {
    id: 64,
    cat: 'family',
    type: 'federal',
    name: 'VA Caregiver Support (PCAFC)',
    desc: 'Financial, health, and support services for caregivers of seriously injured post-9/11 veterans.',
    phone: '(855) 260-3274',
    url: 'https://www.caregiver.va.gov',
    label: 'Learn More',
  },
  {
    id: 65,
    cat: 'family',
    type: 'nonprofit',
    name: 'Blue Star Families',
    desc: 'Connects military families to resources and community. Strong Alabama chapter presence.',
    phone: '',
    url: 'https://bluestarfam.org',
    label: 'Join Now',
  },
  {
    id: 66,
    cat: 'family',
    type: 'state',
    name: 'Alabama Military Family Assistance Fund',
    desc: 'Emergency financial grants for Alabama Guard and Reserve families facing hardship during deployments.',
    phone: '(334) 213-2585',
    url: 'https://dmva.alabama.gov/family-assistance',
    label: 'Apply Now',
  },
  {
    id: 67,
    cat: 'family',
    type: 'nonprofit',
    name: 'National Military Family Association',
    desc: 'Advocacy, research, and programs supporting military families across all branches.',
    phone: '(703) 931-6632',
    url: 'https://www.militaryfamily.org',
    label: 'Learn More',
  },
  {
    id: 85,
    cat: 'family',
    type: 'state',
    name: 'Heroes Welcome Initiative',
    desc: 'State program giving Alabama military families community resources, licensing reciprocity for spouses, and school enrollment support.',
    phone: '',
    url: 'https://www.heroeswelcome.alabama.gov',
    label: 'Visit Website',
  },
  {
    id: 86,
    cat: 'family',
    type: 'nonprofit',
    name: 'Military Spouse Advocacy Network',
    desc: 'Peer-to-peer mentorship 24/7 for military spouses in or relocating to Alabama.',
    phone: '',
    url: 'https://www.militaryspouseadvocacynetwork.org',
    label: 'Connect Now',
  },
  {
    id: 68,
    cat: 'transition',
    type: 'federal',
    name: 'Transition Assistance Program (TAP)',
    desc: 'Mandatory separation counseling covering VA benefits, employment, education, and finances.',
    phone: '(800) 827-1000',
    url: 'https://www.va.gov/careers-employment/transition-assistance-program',
    label: 'Learn More',
  },
  {
    id: 69,
    cat: 'transition',
    type: 'state',
    name: 'Alabama Veterans Resource Center',
    desc: 'Montgomery center helping veterans transition with career counseling, job placement, and training. Now operating as Mission Forward AL.',
    phone: '(334) 386-5600',
    url: 'https://missionforwardal.org',
    label: 'Visit Website',
  },
  {
    id: 70,
    cat: 'transition',
    type: 'federal',
    name: 'Military Records — National Archives',
    desc: 'Request DD-214s, service records, and other military documents needed for benefits and employment.',
    phone: '(314) 801-0800',
    url: 'https://www.archives.gov/veterans',
    label: 'Request Records',
  },
  {
    id: 71,
    cat: 'transition',
    type: 'nonprofit',
    name: 'Team Red White & Blue',
    desc: 'Enriching the lives of veterans through physical and social activity. Strong Alabama chapter presence.',
    phone: '',
    url: 'https://www.teamrwb.org',
    label: 'Join Now',
  },
  {
    id: 72,
    cat: 'transition',
    type: 'nonprofit',
    name: 'American Corporate Partners (ACP)',
    desc: 'Free year-long mentoring pairing veterans with corporate professionals for career guidance.',
    phone: '(212) 752-0700',
    url: 'https://www.acp-usa.org',
    label: 'Apply Now',
  },
  {
    id: 73,
    cat: 'transition',
    type: 'nonprofit',
    name: 'Hire Heroes USA',
    desc: 'Free career coaching and job placement for transitioning military and veterans.',
    phone: '(877) 663-4872',
    url: 'https://www.hireheroesusa.org',
    label: 'Get Help',
  },
  {
    id: 74,
    cat: 'transition',
    type: 'federal',
    name: 'VA.gov — My VA Portal',
    desc: 'Online portal to access VA benefits, disability ratings, payment history, and medical records. Replaces the retired eBenefits portal.',
    phone: '',
    url: 'https://www.va.gov',
    label: 'Log In',
  },
  {
    id: 78,
    cat: 'ministry',
    type: 'nonprofit',
    name: 'Mighty Oaks Foundation',
    desc: 'Free 5-day faith-based Legacy Program retreats for veterans and first responders struggling with PTSD and moral injury. Travel and lodging included.',
    phone: '(877) 878-4400',
    url: 'https://www.mightyoaksprograms.org',
    label: 'Learn More',
  },
  {
    id: 79,
    cat: 'ministry',
    type: 'local',
    name: 'Call Sign Victor',
    desc: 'Alabama Christian nonprofit serving veterans and first responders through faith-centered retreats and peer support. Annual events at Camp Baldwin, AL.',
    phone: '',
    url: 'https://callsignvictor.org',
    label: 'Visit Website',
  },
  {
    id: 80,
    cat: 'ministry',
    type: 'local',
    name: 'Semper Fi Community Task Force',
    desc: 'All-volunteer North Alabama nonprofit serving veterans, first responders, and Gold Star families. Heroes Week, outdoor adventures, and youth scholarships.',
    phone: '',
    url: 'https://semperfictf.org',
    label: 'Visit Website',
  },
  {
    id: 81,
    cat: 'ministry',
    type: 'nonprofit',
    name: 'Point Man International Ministries',
    desc: 'Faith-based peer outreach connecting veterans and families to local support, counseling, and spiritual care. Alabama chapters available.',
    phone: '(800) 877-8387',
    url: 'https://pointmaninternational.org',
    label: 'Find a Chapter',
  },
  {
    id: 82,
    cat: 'ministry',
    type: 'nonprofit',
    name: 'Mission 22',
    desc: 'Veteran suicide awareness and peer support. Treatment programs, peer support training, and community outreach.',
    phone: '(503) 908-8505',
    url: 'https://mission22.com',
    label: 'Get Support',
  },
  {
    id: 83,
    cat: 'ministry',
    type: 'nonprofit',
    name: 'Warriors Heart',
    desc: 'Faith-and-recovery treatment for active military, veterans, and first responders dealing with addiction, PTSD, and co-occurring disorders.',
    phone: '(844) 448-2567',
    url: 'https://www.warriorsheart.com',
    label: 'Learn More',
  },
  {
    id: 84,
    cat: 'ministry',
    type: 'nonprofit',
    name: 'Warrior PATHH — Boulder Crest',
    desc: 'Free Post-Traumatic Growth program for combat veterans and first responders. Residential and virtual tracks.',
    phone: '(540) 554-7442',
    url: 'https://bouldercrest.org/programs',
    label: 'Apply Now',
  },
  {
    id: 99,
    cat: 'women',
    type: 'federal',
    name: 'VA Women Veterans Call Center',
    desc: 'Free, confidential help connecting women veterans to VA benefits, health care, and local Women Veterans Program Managers. Call or text the same number.',
    phone: '(855) 829-6636',
    url: 'https://www.womenshealth.va.gov/wvcc.asp',
    label: 'Call or Text',
  },
  {
    id: 100,
    cat: 'women',
    type: 'federal',
    name: 'Center for Women Veterans',
    desc: 'VA office that monitors programs for women veterans and connects them to benefits, health care, and recognition for their service.',
    phone: '',
    url: 'https://www.va.gov/womenvet/',
    label: 'Learn More',
  },
  {
    id: 101,
    cat: 'women',
    type: 'federal',
    name: 'Women Veterans Health Care',
    desc: 'Comprehensive VA health services built for women veterans, including primary care, reproductive health, and care related to military sexual trauma.',
    phone: '',
    url: 'https://www.womenshealth.va.gov',
    label: 'Learn More',
  },
  {
    id: 102,
    cat: 'women',
    type: 'nonprofit',
    name: 'Final Salute Inc.',
    desc: 'Safe housing and financial support for women veterans and their children facing or at risk of homelessness.',
    phone: '',
    url: 'https://www.finalsaluteinc.org',
    label: 'Get Help',
  },
  {
    id: 103,
    cat: 'adaptive',
    type: 'local',
    name: 'Lakeshore Foundation — Lima Foxtrot',
    desc: 'Birmingham-based Olympic and Paralympic training site offering free adaptive sports, fitness, and recreation for injured service members and veterans.',
    phone: '(205) 313-7400',
    url: 'https://www.lakeshore.org/activity/veterans/',
    label: 'Explore Programs',
  },
  {
    id: 104,
    cat: 'adaptive',
    type: 'nonprofit',
    name: 'Move United',
    desc: 'National network connecting veterans and people with disabilities to adaptive sports and recreation programs across the country.',
    phone: '',
    url: 'https://moveunitedsport.org',
    label: 'Find a Program',
  },
  {
    id: 105,
    cat: 'adaptive',
    type: 'federal',
    name: 'National Veterans Wheelchair Games',
    desc: 'Annual adaptive sports competition for veterans who use wheelchairs, presented by the VA and Paralyzed Veterans of America.',
    phone: '',
    url: 'https://wheelchairgames.org',
    label: 'Learn More',
  },
  {
    id: 106,
    cat: 'adaptive',
    type: 'nonprofit',
    name: 'Wounded Warrior Project — Health & Wellness',
    desc: 'Free fitness, adaptive sports, and outdoor programs for wounded post-9/11 veterans.',
    phone: '(888) 997-2586',
    url: 'https://www.woundedwarriorproject.org',
    label: 'Learn More',
  },
  {
    id: 107,
    cat: 'recovery',
    type: 'hotline',
    name: 'SAMHSA National Helpline',
    desc: 'Free, confidential, 24/7 treatment referral and information for substance use and mental health, in English and Spanish.',
    phone: '(800) 662-4357',
    url: 'https://www.samhsa.gov/find-help/helplines/national-helpline',
    label: 'Get Help Now',
  },
  {
    id: 108,
    cat: 'recovery',
    type: 'federal',
    name: 'VA Substance Use Disorder Treatment',
    desc: 'VA treatment for alcohol and drug problems, including counseling, medication-assisted treatment, and outpatient or residential care.',
    phone: '',
    url: 'https://www.mentalhealth.va.gov/substance-use/',
    label: 'Learn More',
  },
  {
    id: 109,
    cat: 'recovery',
    type: 'state',
    name: 'Alabama Dept. of Mental Health — Substance Use',
    desc: 'State substance use treatment and recovery services across Alabama, including outpatient care and crisis support.',
    phone: '(800) 367-0955',
    url: 'https://mh.alabama.gov',
    label: 'Learn More',
  },
  {
    id: 110,
    cat: 'recovery',
    type: 'federal',
    name: 'Make the Connection',
    desc: 'VA resource with real veteran stories and a locator that connects veterans to mental health and substance use support.',
    phone: '',
    url: 'https://www.maketheconnection.net',
    label: 'Visit Website',
  },
  {
    id: 111,
    cat: 'recovery',
    type: 'local',
    name: 'Bradford Health — Hero&rsquo;s Path',
    desc: 'Veteran and active-duty substance use treatment at Bradford&rsquo;s Alabama residential campuses (including Warrior and Madison near Huntsville). VA Community Care Network and TRICARE accepted.',
    phone: '(888) 424-3761',
    url: 'https://heros-path.com',
    label: 'Learn More',
  },
  {
    id: 112,
    cat: 'recovery',
    type: 'local',
    name: 'The Foundry Ministries',
    desc: 'Faith-based long-term residential recovery for men and women, plus an emergency shelter and job-readiness training. Locations in Bessemer, Birmingham, and Cullman.',
    phone: '',
    url: 'https://foundryministries.com',
    label: 'Learn More',
  },
  {
    id: 113,
    cat: 'legal',
    type: 'nonprofit',
    name: 'C-VETS — Cumberland Veterans Legal Clinic',
    desc: 'Free civil legal help (consumer debt, landlord-tenant, family law, wills, expungement) for veterans and families across an 8-county area of north-central Alabama. Run by Samford&rsquo;s Cumberland School of Law.',
    phone: '(205) 726-4735',
    url: 'https://www.samford.edu/law/c-vets',
    label: 'Apply for Help',
  },
  {
    id: 114,
    cat: 'legal',
    type: 'state',
    name: 'Alabama Veterans Treatment Courts',
    desc: 'Court programs in 28+ Alabama counties focused on treatment and rehabilitation rather than incarceration for justice-involved veterans facing substance use or mental health challenges. Administered through the ADVA.',
    phone: '',
    url: 'https://va.alabama.gov/vtc/',
    label: 'Learn More',
  },
  {
    id: 115,
    cat: 'employment',
    type: 'nonprofit',
    name: 'Still Serving Veterans',
    desc: 'Huntsville-based nonprofit (offices in Huntsville and Phenix City) offering free career transition help, resume and interview prep, job placement, and VA benefits counseling.',
    phone: '(256) 883-7035',
    url: 'https://ssv.org',
    label: 'Get Help',
  },
  {
    id: 116,
    cat: 'housing',
    type: 'local',
    name: 'Three Hots and a Cot',
    desc: 'Birmingham nonprofit founded by veterans, providing transitional and independent housing, meals, counseling, and job placement for homeless veterans.',
    phone: '(205) 520-2356',
    url: 'https://www.cotsforvets.org',
    label: 'Learn More',
  },
  {
    id: 117,
    cat: 'transition',
    type: 'nonprofit',
    name: 'America&rsquo;s Warrior Partnership',
    desc: 'Connects veterans and families to vetted local and national resources through its community-integration network, with a focus on preventing veteran suicide.',
    phone: '',
    url: 'https://www.americaswarriorpartnership.org',
    label: 'Visit Website',
  },
  {
    id: 118,
    cat: 'crisis',
    type: 'state',
    name: 'The Victory Center — Jax State',
    desc: 'Jacksonville State University center serving veterans and families across a 15-county region with mental health counseling (in person and telehealth), case management, social support, and workforce development.',
    phone: '',
    url: 'https://www.jsu.edu/victorycenter/',
    label: 'Learn More',
  },
  {
    id: 119,
    cat: 'employment',
    type: 'nonprofit',
    name: 'Helmets to Hardhats',
    desc: 'National program connecting veterans, Guard, and Reserve members to no-cost apprenticeships and careers in the construction building trades (electrical, plumbing, carpentry, and more). Earn while you learn.',
    phone: '',
    url: 'https://www.helmetstohardhats.org',
    label: 'Get Started',
  },
  {
    id: 120,
    cat: 'ministry',
    type: 'local',
    name: 'Turning Point Foundation — Thorsby, AL',
    desc: 'Faith-based, Christ-centered 90-day residential recovery program for men south of Birmingham, blending a 12-step curriculum with spiritual growth. (Also listed under Substance Use &amp; Recovery.)',
    phone: '(205) 955-2890',
    url: 'https://www.turningpointal.org',
    label: 'Learn More',
  },
  {
    id: 121,
    cat: 'ministry',
    type: 'local',
    name: 'The Foundry Ministries',
    desc: 'Faith-based, Christ-centered residential recovery for men and women in the Birmingham area, with spiritual guidance, life skills, and job readiness. (Also listed under Substance Use &amp; Recovery.)',
    phone: '',
    url: 'https://foundryministries.com',
    label: 'Learn More',
  },
  {
    id: 122,
    cat: 'family',
    type: 'nonprofit',
    name: 'Fisher House Foundation',
    desc: 'Free lodging for veteran and military families while a loved one receives care at a VA or military medical center, for the full duration of treatment.',
    phone: '',
    url: 'https://www.fisherhouse.org',
    label: 'Learn More',
  },
  {
    id: 123,
    cat: 'servicedogs',
    type: 'nonprofit',
    name: 'K9s For Warriors',
    desc: 'Provides trained service dogs at no cost to veterans living with PTSD, traumatic brain injury, or military sexual trauma, through a residential pairing program.',
    phone: '',
    url: 'https://k9sforwarriors.org',
    label: 'Learn More',
  },
  {
    id: 124,
    cat: 'financial',
    type: 'nonprofit',
    name: 'Soldiers&rsquo; Angels',
    desc: 'National nonprofit with a seat on the VA advisory council offering veteran food assistance, box lunches, and support programs for service members, veterans, and their families.',
    phone: '',
    url: 'https://soldiersangels.org',
    label: 'Get Support',
  },
  {
    id: 125,
    cat: 'family',
    type: 'nonprofit',
    name: 'The Independence Fund',
    desc: 'Supports catastrophically wounded veterans and their caregivers with all-terrain mobility devices, caregiver networks, advocacy, and emergency assistance.',
    phone: '',
    url: 'https://independencefund.org',
    label: 'Learn More',
  },
  {
    id: 126,
    cat: 'servicedogs',
    type: 'nonprofit',
    name: 'Warrior Freedom Service Dogs',
    desc: 'Provides trained service dogs at no cost to combat veterans with PTSD or traumatic brain injury across Tennessee, Georgia, and Alabama. Veterans help train their own dog to ADA standards.',
    phone: '',
    url: 'https://www.warriorfreedom.org',
    label: 'Learn More',
  },
  {
    id: 127,
    cat: 'servicedogs',
    type: 'local',
    name: 'Service Dogs Alabama',
    desc: 'Alabama nonprofit that trains and places service dogs free of charge for people, including veterans, with PTSD, mobility, seizure, and other needs. Application and wait list apply.',
    phone: '',
    url: 'https://www.servicedogsalabama.org',
    label: 'Apply',
  },
  {
    id: 128,
    cat: 'servicedogs',
    type: 'nonprofit',
    name: 'America&rsquo;s VetDogs',
    desc: 'Provides guide and service dogs at no cost to veterans and first responders, including dogs for PTSD, mobility, and hearing needs.',
    phone: '',
    url: 'https://www.vetdogs.org',
    label: 'Learn More',
  },
  {
    id: 129,
    cat: 'recovery',
    type: 'nonprofit',
    name: 'Aletheia House',
    desc: 'Alabama substance abuse treatment provider since 1972 offering residential and outpatient care plus veteran-specific job support programs. Headquartered in Birmingham with locations statewide.',
    phone: '(205) 324-6502',
    url: 'https://www.specialkindofcaring.org',
    label: 'Learn More',
  },
  {
    id: 130,
    cat: 'crisis',
    type: 'nonprofit',
    name: 'Wings Across Alabama — Veteran Peer Support',
    desc: 'Free veteran-led mental health peer support groups statewide plus a 24/7 non-crisis warm line, funded through an ADVA grant.',
    phone: '(844) 999-4647',
    url: 'https://wingsacrossal.org/veterans-across-alabama/',
    label: 'Get Support',
  },
  {
    id: 131,
    cat: 'crisis',
    type: 'nonprofit',
    name: 'Stop Soldier Suicide',
    desc: 'Free, confidential telehealth mental health care for service members and veterans in all 50 states, regardless of discharge status.',
    phone: '(844) 889-5610',
    url: 'https://stopsoldiersuicide.org',
    label: 'Get Help',
  },
  {
    id: 132,
    cat: 'housing',
    type: 'local',
    name: 'PEERS Caring Home for Veterans',
    desc: 'Montgomery nonprofit providing housing plus financial, mental, and physical support for homeless veterans.',
    phone: '(334) 201-8706',
    url: 'https://peersamerica.org',
    label: 'Learn More',
  },
  {
    id: 133,
    cat: 'housing',
    type: 'nonprofit',
    name: 'Tunnel to Towers — Homeless Veteran Program',
    desc: 'National case management network for homeless veterans, with a 110-unit Birmingham Veteran Village offering housing and support services opening in early 2027.',
    phone: '(718) 987-1931',
    url: 'https://t2t.org',
    label: 'Learn More',
  },
  {
    id: 134,
    cat: 'legal',
    type: 'nonprofit',
    name: 'Alabama State Bar — Volunteer Lawyers Program',
    desc: 'Free civil legal assistance for low-income Alabamians, including veterans and military families, through a statewide volunteer attorney network.',
    phone: '(888) 857-8571',
    url: 'https://www.alabar.org/programs/volunteer-lawyers-program/',
    label: 'Get Help',
  },
  {
    id: 135,
    cat: 'women',
    type: 'local',
    name: 'Invisible Warriors',
    desc: 'Madison-based nonprofit for women veterans offering Alabama&rsquo;s only women-only PTSD support group, trauma-informed retreats, workshops, and a Military Women&rsquo;s Community Center.',
    phone: '(269) 319-6041',
    url: 'https://invisiblewarriors.org',
    label: 'Learn More',
  },
  {
    id: 136,
    cat: 'ministry',
    type: 'nonprofit',
    name: 'REBOOT Recovery',
    desc: 'Free 12-week faith-based, peer-led trauma healing course for veterans, active duty, and families. In-person Alabama locations and virtual options.',
    phone: '(931) 292-2011',
    url: 'https://rebootrecovery.com',
    label: 'Find a Course',
  },
  {
    id: 137,
    cat: 'adaptive',
    type: 'local',
    name: 'WarHawgs — Dothan, AL',
    desc: 'Wiregrass nonprofit providing outdoor retreats and adaptive hunting, fishing, and sports programs for disabled veterans, active duty, and first responders.',
    phone: '(855) 927-4294',
    url: 'https://warhawgs.org',
    label: 'Learn More',
  },
];
const BADGE_LABELS = {
  federal: 'Federal',
  state: 'State',
  local: 'Local',
  nonprofit: 'Nonprofit',
  hotline: 'Hotline',
};
function buildCard(r) {
  const phone = r.phone ? `<div class="rc-phone">📞 ${r.phone}</div>` : '';
  return `<a href="${r.url}" target="_blank" rel="noopener" class="res-card" data-cat="${r.cat}" data-type="${r.type}" data-name="${r.name.toLowerCase()}" data-desc="${r.desc.toLowerCase()}"><div class="rc-head"><div class="rc-name">${r.name}</div><span class="rc-badge badge-${r.type}">${BADGE_LABELS[r.type]}</span></div>
${phone}
<div class="rc-desc">${r.desc}</div><div class="rc-link">→ ${r.label}</div></a>`;
}
function populateGrids() {
  document.getElementById('all-grid').innerHTML = RESOURCES.map(buildCard).join('');
  [
    'crisis',
    'vetcenters',
    'housing',
    'benefits',
    'education',
    'employment',
    'financial',
    'legal',
    'family',
    'transition',
    'ministry',
    'women',
    'adaptive',
    'recovery',
    'servicedogs',
  ].forEach((cat) => {
    const g = document.getElementById(cat + '-grid');
    if (g)
      g.innerHTML = RESOURCES.filter((r) => r.cat === cat)
        .map(buildCard)
        .join('');
  });
}
function showSection(id, btn) {
  document.querySelectorAll('.cat-section').forEach((s) => s.classList.remove('visible'));
  document.querySelectorAll('.cat-btn').forEach((b) => b.classList.remove('active'));
  const sec = document.getElementById('section-' + id);
  if (sec) sec.classList.add('visible');
  if (btn) btn.classList.add('active');
  const searchInput = document.getElementById('search-input');
  if (searchInput) searchInput.value = '';
  showAllCards();
  document.getElementById('no-results')?.classList.remove('visible');
  const categoryNavigation = document.querySelector('.cat-nav-wrap');
  if (categoryNavigation) {
    window.scrollTo({ top: categoryNavigation.offsetTop - 10, behavior: 'smooth' });
  }
}
function filterType(type, btn) {
  document.querySelectorAll('.filter-row .f-btn').forEach((b) => b.classList.remove('active'));
  btn?.classList.add('active');
  document.querySelectorAll('#all-grid .res-card').forEach((c) => {
    c.classList.toggle('hidden-res', type !== 'all' && c.dataset.type !== type);
  });
  checkNoResults();
}
function handleSearch(val) {
  const q = val.toLowerCase().trim();
  document.querySelectorAll('.cat-section').forEach((s) => s.classList.remove('visible'));
  document.querySelectorAll('.cat-btn').forEach((b) => b.classList.remove('active'));
  var _as = document.getElementById('section-all');
  if (_as) _as.classList.add('visible');
  var _ab = document.querySelector('.cat-btn');
  if (_ab) _ab.classList.add('active');
  if (!q) {
    showAllCards();
    document.getElementById('no-results')?.classList.remove('visible');
    return;
  }
  let found = 0;
  document.querySelectorAll('#all-grid .res-card').forEach((c) => {
    const match =
      c.dataset.name.includes(q) ||
      c.dataset.desc.includes(q) ||
      c.dataset.cat.includes(q) ||
      c.dataset.type.includes(q);
    c.classList.toggle('hidden-res', !match);
    if (match) found++;
  });
  document.getElementById('no-results').classList.toggle('visible', found === 0);
  document.querySelectorAll('.filter-row .f-btn').forEach((b) => b.classList.remove('active'));
  document.querySelector('.filter-row .f-btn')?.classList.add('active');
}
function showAllCards() {
  document.querySelectorAll('#all-grid .res-card').forEach((c) => c.classList.remove('hidden-res'));
}
function checkNoResults() {
  const v = document.querySelectorAll('#all-grid .res-card:not(.hidden-res)').length;
  document.getElementById('no-results').classList.toggle('visible', v === 0);
}
document.addEventListener('DOMContentLoaded', () => {
  populateGrids();

  document.querySelectorAll('[data-resource-section]').forEach((button) => {
    button.addEventListener('click', () => showSection(button.dataset.resourceSection, button));
  });
  document.querySelectorAll('[data-resource-filter]').forEach((button) => {
    button.addEventListener('click', () => filterType(button.dataset.resourceFilter, button));
  });

  const searchInput = document.getElementById('search-input');
  searchInput?.addEventListener('input', () => handleSearch(searchInput.value));
  document
    .querySelector('[data-resource-search]')
    ?.addEventListener('click', () => handleSearch(searchInput?.value || ''));
  document.querySelector('[data-print-page]')?.addEventListener('click', () => window.print());
});
